/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package gradle.tag.task

import gradle.tag.task.GitUtils
import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
class GradleTagTaskPlugin implements Plugin<Project> {
    void apply(Project project) {
        // Register a task
        project.tasks.register("checkGitStatus", CheckGitStatus) {
            setGroup("release")
        }

        project.tasks.register("createMinorRelease", CreateMinorRelease) {
            dependsOn("checkGitStatus")
            setGroup("release")
        }

        project.tasks.register("createMajorRelease", CreateMajorRelease) {
            dependsOn("checkGitStatus")
            setGroup("release")
        }
        project.tasks.register("releaseTask") {
            setGroup("release")
            def branch = GitUtils.currentBranch
            if (branch.contains("master")) {
                dependsOn("createMajorRelease")
            } else {
                dependsOn("createMinorRelease")
            }
        }
    }
}
